#!/bin/bash

INPUT=$1
SECTION=$2
OUTPUT=$1.o
HEADER=$1.h

objcopy -I binary -O elf32-i386 -B i386 --rename-section .data=$SECTION,alloc,load,readonly,data,contents $INPUT $OUTPUT

SYMBOLS=$(nm -n $OUTPUT | cut -d" " -f3)

SYM_START=$(echo $SYMBOLS | egrep -o "[[:alpha:]_]+_start")
SYM_END=$(echo $SYMBOLS | egrep -o "[[:alpha:]_]+_end")
SYM_SIZE=$(echo $SYMBOLS | egrep -o "[[:alpha:]_]+_size")

SEC_SYMBOL=$(echo $SECTION | sed "s/[^[:alpha:]]/_/g")
HEADER_GUARD=ELFEMBED_$(echo $HEADER | sed "s/[^[:alpha:]]/_/g" | tr "[:lower:]" "[:upper:]")

echo "/* Generated by $(basename $0) $(date +%Y-%m-%d_%H-%M-%S) */" > $HEADER
echo "#ifndef $HEADER_GUARD" >> $HEADER
echo "#define $HEADER_GUARD" >> $HEADER
echo "" >> $HEADER
echo "#ifdef __cplusplus" >> $HEADER
echo "extern \"C\"{" >> $HEADER
echo "#endif" >> $HEADER
echo "__attribute__((unused)) extern char $SYM_START;" >> $HEADER
echo "__attribute__((unused)) extern char $SYM_END;" >> $HEADER
echo "__attribute__((unused)) extern char $SYM_SIZE;" >> $HEADER
echo "#ifdef __cplusplus" >> $HEADER
echo "}" >> $HEADER
echo "#endif" >> $HEADER
echo "" >> $HEADER
echo "__attribute__((unused)) static const char *const ${SEC_SYMBOL}_data = &$SYM_START;" >> $HEADER
echo "__attribute__((unused)) static const size_t ${SEC_SYMBOL}_size = (size_t)&$SYM_SIZE;" >> $HEADER
echo "" >> $HEADER
echo "#endif //$HEADER_GUARD" >> $HEADER
