# All makefile fragments assume that $(srcdir) points to the gcc
# directory, not the language subdir
srcdir = ../../../gcc-4.8.1/gcc
-include ./gcc-interface/Makefile
-include ../gcc-interface/Makefile
